[workspace]
members = ["bitcoin", "hashes", "internals", "fuzz", "io"]
resolver = "2"

[patch.crates-io.bitcoin]
path = "bitcoin"

[patch.crates-io.bitcoin_hashes]
path = "hashes"

[patch.crates-io.bitcoin-internals]
path = "internals"

[patch.crates-io.bitcoin-io]
path = "io"
